export const AuditActionType = {
    LOCK_DEVICE: "LOCK_DEVICE",
    UNLOCK_DEVICE: "UNLOCK_DEVICE",
    UPDATE_SCREEN_TIME: "UPDATE_SCREEN_TIME",
    APPROVE_REQUEST: "APPROVE_REQUEST",
    REJECT_REQUEST: "REJECT_REQUEST",
    CHILD_ADDED: "CHILD_ADDED",
    CHILD_DELETED: "CHILD_DELETED",
    CHILD_PROFILE_UPDATED: "CHILD_PROFILE_UPDATED",
    DEVICE_RENAMED: "DEVICE_RENAMED",
    DEVICE_DELETED: "DEVICE_DELETED",
    DEVICE_ADDED: "DEVICE_ADDED"
};